// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hopmeovstqklfquhyhgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcG1lb3ZzdHFrbGZxdWh5aGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTc0NTEsImV4cCI6MjA1OTkzMzQ1MX0.SBwBwbRFEA47F-q71Clr3lnoBpl3msfYYh051WD8fco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);